image:
  repository: 926833232050.dkr.ecr.eu-central-1.amazonaws.com/vault
  tag: 1.9.2-0.1.0
  pullPolicy: IfNotPresent

imagePullSecrets: []

basicAuthSecret: ""
vaultPodSelector: app.kubernetes.io/instance=hc-vault
vaultServiceAccount: hc-vault

rbac:
  create: true

env: {}
#  DYNAMODB_HA_ENABLED: true
#  INSTANCE: hc-vault
#  AWS_DEFAULT_REGION: eu-central-1
#  AWS_DYNAMODB_TABLE: mks-vault-table

secretEnv: {}
#  AWS_SECRET_ACCESS_KEY: ''
#  AWS_ACCESS_KEY_ID: ''

extraSecretEnvironmentVars: []
#    - name: AWS_SECRET_ACCESS_KEY
#    valueFrom:
#      secretKeyRef:
#        name: vault-secret-env
#        key: AWS_SECRET_ACCESS_KEY
#  - name: AWS_ACCESS_KEY_ID
#    valueFrom:
#      secretKeyRef:
#        name: vault-secret-env
#        key: AWS_ACCESS_KEY_ID


prometheusNamespace: prometheus
grafanaDashboardLabels:
  grafana_dashboard: "1"

authmethods:
  userpass: {}
    #prometheus: |-
    #  {
    #    "namespaces":
    #      [ 
    #        "hc-vault"
    #      ],
    #    "acls":
    #      [
    #        "prometheus-metrics"
    #      ]
    #  }

vaultSecretEngines: []
  # - name: pki
  #   parameters: -max-lease-ttl=8760h
