image:
  repository: ghcr.io/casa-delle-coccinelle/vault-config
  tag: 1.12.0-0.1.1
  pullPolicy: IfNotPresent

imagePullSecrets: []

basicAuthSecret: ""
vaultPodSelector: app.kubernetes.io/instance=hc-vault
vaultServiceAccount: hc-vault

rbac:
  create: true

env: {}
#  DYNAMODB_HA_ENABLED: true
#  INSTANCE: hc-vault
#  AWS_DEFAULT_REGION: eu-central-1
#  AWS_DYNAMODB_TABLE: mks-vault-table

secretEnv: {}
#  AWS_SECRET_ACCESS_KEY: ''
#  AWS_ACCESS_KEY_ID: ''

extraSecretEnvironmentVars: []
#    - name: AWS_SECRET_ACCESS_KEY
#    valueFrom:
#      secretKeyRef:
#        name: vault-secret-env
#        key: AWS_SECRET_ACCESS_KEY
#  - name: AWS_ACCESS_KEY_ID
#    valueFrom:
#      secretKeyRef:
#        name: vault-secret-env
#        key: AWS_ACCESS_KEY_ID


prometheusNamespace: prometheus
grafanaNamespace: "{{ .Values.prometheusNamespace }}"
grafanaDashboardLabels:
  grafana_dashboard: "1"

authmethods:
  userpass: {}
    #prometheus: |-
    #  {
    #    "namespaces":
    #      [ 
    #        "hc-vault"
    #      ],
    #    "acls":
    #      [
    #        "prometheus-metrics"
    #      ]
    #  }
  kubernetes: {}
    #prometheus: |-
    #  {
    #    "namespace": "prometheus",
    #    "sa-name": "prometheus-kube-prometheus-prometheus",
    #    "acls":
    #      [
    #        "prometheus-metrics"
    #      ]
    #  }

entities: {}
# prometheus: |-
#   {
#     "name": "prometheus",
#     "aliases": [
#       {
#         "name": "prometheus",
#         "authMethod": "userpass"
#       },
#       {
#         "name": "prometheus",
#         "authMethod": "ali2"
#       }
#     ]
#   }


groups: {}
#groups:
#  admins: |-
#    {
#      "name": "admins",
#      "entities": [
#        "dimitko",
#        "nelinda"
#      ],
#      "acls": [
#        "admins"
#      ]
#    }


vaultSecretEngines: []
  # - name: pki
  #   parameters: -max-lease-ttl=8760h
