{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: [ "get", "list" ]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: [ "get", "list", "watch", "create", "update", "patch" ]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: [ "get", "list", "watch",  "create" ]
  # TODO: Secrets and Service accounts
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  apiGroup: ""
roleRef:
  kind: Role 
  name: {{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  apiGroup: ""
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io

---
# HC Vault's SA needs additional ClusterRoleBinding. Don't know why it's not in Vault's chart
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Release.Name }}-{{ .Values.vaultServiceAccount }}"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.vaultServiceAccount }}
    namespace: {{ .Release.Namespace }}
    apiGroup: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
{{- end -}}
